# Generated by Django 6.0.2 on 2026-02-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="location",
            name="user",
        ),
        migrations.AlterField(
            model_name="location",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
